package hu.akusius.palenque.anigifmaker.ui;

import hu.akusius.palenque.anigifmaker.GenerateParams;
import hu.akusius.palenque.anigifmaker.GifMaker;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Bujdosó Ákos
 */
public class GenerateDialog extends javax.swing.JDialog {

  /** Creates new form GenerateDialog
   * @param parent
   */
  private GenerateDialog(Window parent) {
    super(parent, ModalityType.APPLICATION_MODAL);
    initComponents();

    setLocationRelativeTo(parent);
  }

  /**
   * A GIF-fájl legenerálása.
   * @param parent
   * @param params A generálási paraméterek.
   * @param dest A célfájl.
   */
  public static void generate(Window parent, GenerateParams params, File dest) {
    final GenerateDialog dlg = new GenerateDialog(parent);
    dlg.pbProgress.setMinimum(0);
    dlg.pbProgress.setMaximum(100);
    try {
      final SwingWorker<Void, Void> sw = GifMaker.makeGifAsync(params, dest);

      dlg.btnCancel.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          sw.cancel(false);
        }
      });

      sw.addPropertyChangeListener(new PropertyChangeListener() {
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
          String propName = evt.getPropertyName();
          switch (propName) {
            case "progress":
              dlg.pbProgress.setValue(sw.getProgress());
              break;
            case "state":
              if (sw.getState() == SwingWorker.StateValue.DONE) {
                dlg.dispose();
              }
              break;
          }
        }
      });

      dlg.setVisible(true);
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(parent, "Error occured during generation!", "Error", JOptionPane.WARNING_MESSAGE);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pbProgress = new javax.swing.JProgressBar();
    btnCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Generating…");
    setResizable(false);

    pbProgress.setStringPainted(true);

    btnCancel.setText("Cancel");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(pbProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(150, 150, 150)
        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(150, 150, 150))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(pbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
        .addComponent(btnCancel)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JProgressBar pbProgress;
  // End of variables declaration//GEN-END:variables
}
